<?php

// File generated from our OpenAPI spec

namespace TCStripe\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \TCStripe\Account::OBJECT_NAME => \TCStripe\Account::class,
        \TCStripe\AccountLink::OBJECT_NAME => \TCStripe\AccountLink::class,
        \TCStripe\AlipayAccount::OBJECT_NAME => \TCStripe\AlipayAccount::class,
        \TCStripe\ApplePayDomain::OBJECT_NAME => \TCStripe\ApplePayDomain::class,
        \TCStripe\ApplicationFee::OBJECT_NAME => \TCStripe\ApplicationFee::class,
        \TCStripe\ApplicationFeeRefund::OBJECT_NAME => \TCStripe\ApplicationFeeRefund::class,
        \TCStripe\Balance::OBJECT_NAME => \TCStripe\Balance::class,
        \TCStripe\BalanceTransaction::OBJECT_NAME => \TCStripe\BalanceTransaction::class,
        \TCStripe\BankAccount::OBJECT_NAME => \TCStripe\BankAccount::class,
        \TCStripe\BillingPortal\Session::OBJECT_NAME => \TCStripe\BillingPortal\Session::class,
        \TCStripe\BitcoinReceiver::OBJECT_NAME => \TCStripe\BitcoinReceiver::class,
        \TCStripe\BitcoinTransaction::OBJECT_NAME => \TCStripe\BitcoinTransaction::class,
        \TCStripe\Capability::OBJECT_NAME => \TCStripe\Capability::class,
        \TCStripe\Card::OBJECT_NAME => \TCStripe\Card::class,
        \TCStripe\Charge::OBJECT_NAME => \TCStripe\Charge::class,
        \TCStripe\Checkout\Session::OBJECT_NAME => \TCStripe\Checkout\Session::class,
        \TCStripe\Collection::OBJECT_NAME => \TCStripe\Collection::class,
        \TCStripe\CountrySpec::OBJECT_NAME => \TCStripe\CountrySpec::class,
        \TCStripe\Coupon::OBJECT_NAME => \TCStripe\Coupon::class,
        \TCStripe\CreditNote::OBJECT_NAME => \TCStripe\CreditNote::class,
        \TCStripe\CreditNoteLineItem::OBJECT_NAME => \TCStripe\CreditNoteLineItem::class,
        \TCStripe\Customer::OBJECT_NAME => \TCStripe\Customer::class,
        \TCStripe\CustomerBalanceTransaction::OBJECT_NAME => \TCStripe\CustomerBalanceTransaction::class,
        \TCStripe\Discount::OBJECT_NAME => \TCStripe\Discount::class,
        \TCStripe\Dispute::OBJECT_NAME => \TCStripe\Dispute::class,
        \TCStripe\EphemeralKey::OBJECT_NAME => \TCStripe\EphemeralKey::class,
        \TCStripe\Event::OBJECT_NAME => \TCStripe\Event::class,
        \TCStripe\ExchangeRate::OBJECT_NAME => \TCStripe\ExchangeRate::class,
        \TCStripe\File::OBJECT_NAME => \TCStripe\File::class,
        \TCStripe\File::OBJECT_NAME_ALT => \TCStripe\File::class,
        \TCStripe\FileLink::OBJECT_NAME => \TCStripe\FileLink::class,
        \TCStripe\Invoice::OBJECT_NAME => \TCStripe\Invoice::class,
        \TCStripe\InvoiceItem::OBJECT_NAME => \TCStripe\InvoiceItem::class,
        \TCStripe\InvoiceLineItem::OBJECT_NAME => \TCStripe\InvoiceLineItem::class,
        \TCStripe\Issuing\Authorization::OBJECT_NAME => \TCStripe\Issuing\Authorization::class,
        \TCStripe\Issuing\Card::OBJECT_NAME => \TCStripe\Issuing\Card::class,
        \TCStripe\Issuing\CardDetails::OBJECT_NAME => \TCStripe\Issuing\CardDetails::class,
        \TCStripe\Issuing\Cardholder::OBJECT_NAME => \TCStripe\Issuing\Cardholder::class,
        \TCStripe\Issuing\Dispute::OBJECT_NAME => \TCStripe\Issuing\Dispute::class,
        \TCStripe\Issuing\Transaction::OBJECT_NAME => \TCStripe\Issuing\Transaction::class,
        \TCStripe\LineItem::OBJECT_NAME => \TCStripe\LineItem::class,
        \TCStripe\LoginLink::OBJECT_NAME => \TCStripe\LoginLink::class,
        \TCStripe\Mandate::OBJECT_NAME => \TCStripe\Mandate::class,
        \TCStripe\Order::OBJECT_NAME => \TCStripe\Order::class,
        \TCStripe\OrderItem::OBJECT_NAME => \TCStripe\OrderItem::class,
        \TCStripe\OrderReturn::OBJECT_NAME => \TCStripe\OrderReturn::class,
        \TCStripe\PaymentIntent::OBJECT_NAME => \TCStripe\PaymentIntent::class,
        \TCStripe\PaymentMethod::OBJECT_NAME => \TCStripe\PaymentMethod::class,
        \TCStripe\Payout::OBJECT_NAME => \TCStripe\Payout::class,
        \TCStripe\Person::OBJECT_NAME => \TCStripe\Person::class,
        \TCStripe\Plan::OBJECT_NAME => \TCStripe\Plan::class,
        \TCStripe\Price::OBJECT_NAME => \TCStripe\Price::class,
        \TCStripe\Product::OBJECT_NAME => \TCStripe\Product::class,
        \TCStripe\PromotionCode::OBJECT_NAME => \TCStripe\PromotionCode::class,
        \TCStripe\Radar\EarlyFraudWarning::OBJECT_NAME => \TCStripe\Radar\EarlyFraudWarning::class,
        \TCStripe\Radar\ValueList::OBJECT_NAME => \TCStripe\Radar\ValueList::class,
        \TCStripe\Radar\ValueListItem::OBJECT_NAME => \TCStripe\Radar\ValueListItem::class,
        \TCStripe\Recipient::OBJECT_NAME => \TCStripe\Recipient::class,
        \TCStripe\RecipientTransfer::OBJECT_NAME => \TCStripe\RecipientTransfer::class,
        \TCStripe\Refund::OBJECT_NAME => \TCStripe\Refund::class,
        \TCStripe\Reporting\ReportRun::OBJECT_NAME => \TCStripe\Reporting\ReportRun::class,
        \TCStripe\Reporting\ReportType::OBJECT_NAME => \TCStripe\Reporting\ReportType::class,
        \TCStripe\Review::OBJECT_NAME => \TCStripe\Review::class,
        \TCStripe\SetupIntent::OBJECT_NAME => \TCStripe\SetupIntent::class,
        \TCStripe\Sigma\ScheduledQueryRun::OBJECT_NAME => \TCStripe\Sigma\ScheduledQueryRun::class,
        \TCStripe\SKU::OBJECT_NAME => \TCStripe\SKU::class,
        \TCStripe\Source::OBJECT_NAME => \TCStripe\Source::class,
        \TCStripe\SourceTransaction::OBJECT_NAME => \TCStripe\SourceTransaction::class,
        \TCStripe\Subscription::OBJECT_NAME => \TCStripe\Subscription::class,
        \TCStripe\SubscriptionItem::OBJECT_NAME => \TCStripe\SubscriptionItem::class,
        \TCStripe\SubscriptionSchedule::OBJECT_NAME => \TCStripe\SubscriptionSchedule::class,
        \TCStripe\TaxId::OBJECT_NAME => \TCStripe\TaxId::class,
        \TCStripe\TaxRate::OBJECT_NAME => \TCStripe\TaxRate::class,
        \TCStripe\Terminal\ConnectionToken::OBJECT_NAME => \TCStripe\Terminal\ConnectionToken::class,
        \TCStripe\Terminal\Location::OBJECT_NAME => \TCStripe\Terminal\Location::class,
        \TCStripe\Terminal\Reader::OBJECT_NAME => \TCStripe\Terminal\Reader::class,
        \TCStripe\ThreeDSecure::OBJECT_NAME => \TCStripe\ThreeDSecure::class,
        \TCStripe\Token::OBJECT_NAME => \TCStripe\Token::class,
        \TCStripe\Topup::OBJECT_NAME => \TCStripe\Topup::class,
        \TCStripe\Transfer::OBJECT_NAME => \TCStripe\Transfer::class,
        \TCStripe\TransferReversal::OBJECT_NAME => \TCStripe\TransferReversal::class,
        \TCStripe\UsageRecord::OBJECT_NAME => \TCStripe\UsageRecord::class,
        \TCStripe\UsageRecordSummary::OBJECT_NAME => \TCStripe\UsageRecordSummary::class,
        \TCStripe\WebhookEndpoint::OBJECT_NAME => \TCStripe\WebhookEndpoint::class,
    ];
}
